CREATE DATABASE HRSYSTEM;
use HRSYSTEM;
CREATE TABLE APL_ECI_ECIVIL (
                ECI_ID INT AUTO_INCREMENT NOT NULL,
                ECI_NOMBRE VARCHAR(15) NOT NULL,
                PRIMARY KEY (ECI_ID)
);

ALTER TABLE APL_ECI_ECIVIL COMMENT 'Estado civil del empleado.';

ALTER TABLE APL_ECI_ECIVIL MODIFY COLUMN ECI_ID INTEGER COMMENT 'Identificador de estado civil.';

ALTER TABLE APL_ECI_ECIVIL MODIFY COLUMN ECI_NOMBRE VARCHAR(15) COMMENT 'Estado civil del emepleado.';


CREATE TABLE APL_CAR_CARGO (
                CAR_ID INT AUTO_INCREMENT NOT NULL,
                CAR_NOMBRE VARCHAR(50) NOT NULL,
                PRIMARY KEY (CAR_ID)
);

ALTER TABLE APL_CAR_CARGO COMMENT 'Tabla para manejar los cargos disponibles de empleado.';

ALTER TABLE APL_CAR_CARGO MODIFY COLUMN CAR_ID INTEGER COMMENT 'Identificador para cargo de empleados.';

ALTER TABLE APL_CAR_CARGO MODIFY COLUMN CAR_NOMBRE VARCHAR(50) COMMENT 'Nombre del cargo disponible para empleado.';


CREATE TABLE APL_EEM_ESTADO_EMPLEADO (
                EEM_ID INT AUTO_INCREMENT NOT NULL,
                EEM_NOMBRE VARCHAR(45) NOT NULL,
                PRIMARY KEY (EEM_ID)
);

ALTER TABLE APL_EEM_ESTADO_EMPLEADO COMMENT 'Tabla para manejar los estados de un empleado.';

ALTER TABLE APL_EEM_ESTADO_EMPLEADO MODIFY COLUMN EEM_ID INTEGER COMMENT 'Identificador para estado de empleado.';

ALTER TABLE APL_EEM_ESTADO_EMPLEADO MODIFY COLUMN EEM_NOMBRE VARCHAR(45) COMMENT 'Nombre del estado de empleado.';


CREATE TABLE APL_SEX_SEXO (
                SEX_ID INT AUTO_INCREMENT NOT NULL,
                SEX_NOMBRE VARCHAR(9) NOT NULL,
                PRIMARY KEY (SEX_ID)
);

ALTER TABLE APL_SEX_SEXO COMMENT 'Tabla para identificar ek sexo de empleado';

ALTER TABLE APL_SEX_SEXO MODIFY COLUMN SEX_ID INTEGER COMMENT 'Identificador de tipo sexo de empleado.';

ALTER TABLE APL_SEX_SEXO MODIFY COLUMN SEX_NOMBRE VARCHAR(9) COMMENT 'Nombre del tipo de sexo disponibles.';


CREATE TABLE APL_EDE_ESTADO_DEP (
                EDE_ID INT AUTO_INCREMENT NOT NULL,
                EDE_NOMBRE VARCHAR(35) NOT NULL,
                PRIMARY KEY (EDE_ID)
);

ALTER TABLE APL_EDE_ESTADO_DEP COMMENT 'Tabla para manejar el estado de los departamentos de la empresa.';

ALTER TABLE APL_EDE_ESTADO_DEP MODIFY COLUMN EDE_ID INTEGER COMMENT 'Identificador de estado para departamento.';

ALTER TABLE APL_EDE_ESTADO_DEP MODIFY COLUMN EDE_NOMBRE VARCHAR(35) COMMENT 'Nombre para estado de departamento.';


CREATE TABLE APL_DEP_DEPARTAMENTO (
                DEP_ID INT AUTO_INCREMENT NOT NULL,
                DEP_NOMBRE VARCHAR(50) NOT NULL,
                EDE_ID INT NOT NULL,
                PRIMARY KEY (DEP_ID)
);

ALTER TABLE APL_DEP_DEPARTAMENTO COMMENT 'Tabla para enformacion relacionada con el departameto de la empresa.';

ALTER TABLE APL_DEP_DEPARTAMENTO MODIFY COLUMN DEP_ID INTEGER COMMENT 'Identificador de departamento.';

ALTER TABLE APL_DEP_DEPARTAMENTO MODIFY COLUMN DEP_NOMBRE VARCHAR(50) COMMENT 'Nombre del departamento.';

ALTER TABLE APL_DEP_DEPARTAMENTO MODIFY COLUMN EDE_ID INTEGER COMMENT 'Identificador de estado para departamento.';


CREATE TABLE APL_EMP_EMPLEADO (
                EMP_ID INT AUTO_INCREMENT NOT NULL,
                EMP_NOMBRE VARCHAR(45) NOT NULL,
                EMP_APELLIDO VARCHAR(45) NOT NULL,
                EMP_CORREO VARCHAR(50) NOT NULL,
                EMP_TELEFONO VARCHAR(8) NOT NULL,
                EMP_DUI VARCHAR(9) NOT NULL,
                EMP_DIRECCION VARCHAR(255) NOT NULL,
                EMP_FECHA_NAC DATE NOT NULL,
                EMP_FECHA_CONTRATO DATE NOT NULL,
                SEX_ID INT NOT NULL,
                EEM_ID INT NOT NULL,
                ECI_ID INT NOT NULL,
                DEP_ID INT NOT NULL,
                CAR_ID INT NOT NULL,
                PRIMARY KEY (EMP_ID)
);

ALTER TABLE APL_EMP_EMPLEADO COMMENT 'Tabla para todos los datos realcionados con empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_ID INTEGER COMMENT 'Identificador de empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_NOMBRE VARCHAR(45) COMMENT 'Nombre del empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_APELLIDO VARCHAR(45) COMMENT 'Apellido del empleado/a.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_CORREO VARCHAR(50) COMMENT 'Correo electronico del empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_TELEFONO VARCHAR(8) COMMENT 'Numero telefonico del empelado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_DUI VARCHAR(9) COMMENT 'Campo para documento de identidad del empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_DIRECCION VARCHAR(255) COMMENT 'Direccion de habitacion del empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_FECHA_NAC DATE COMMENT 'Fecha de nacimiento del empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EMP_FECHA_CONTRATO DATE COMMENT 'Fecha de contratacion de empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN SEX_ID INTEGER COMMENT 'Identificador de tipo sexo de empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN EEM_ID INTEGER COMMENT 'Identificador para estado de empleado.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN ECI_ID INTEGER COMMENT 'Identificador de estado civil.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN DEP_ID INTEGER COMMENT 'Identificador de departamento.';

ALTER TABLE APL_EMP_EMPLEADO MODIFY COLUMN CAR_ID INTEGER COMMENT 'Identificador para cargo de empleados.';


CREATE TABLE APL_PLA_PLANILLA (
                PLA_ID INT AUTO_INCREMENT NOT NULL,
                PLA_AFP_PATRONAL DOUBLE  NOT NULL,
                PLA_AFP_LABORAL DOUBLE  NOT NULL,
                PLA_ISSS_PATRONAL DOUBLE  NOT NULL,
                PLA_ISSS_LABORAL DOUBLE  NOT NULL,
                PLA_RENTA DOUBLE  NOT NULL,
                EMP_ID INT NOT NULL,
                PRIMARY KEY (PLA_ID)
);

ALTER TABLE APL_PLA_PLANILLA COMMENT 'Tabla para manejar la planilla de la empresa.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN PLA_ID INTEGER COMMENT 'Identificador de planilla.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN PLA_AFP_PATRONAL FLOAT COMMENT 'Monto a pagar por la empresa en concepto de AFP patronal.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN PLA_AFP_LABORAL FLOAT COMMENT 'Monto a pagar por el empleado en concepto de AFP personal.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN PLA_ISSS_PATRONAL FLOAT COMMENT 'Monto a pagar por la empresa en concepto de isss patronal.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN PLA_ISSS_LABORAL FLOAT COMMENT 'Monto a pagar por el empleado en concepto de isss personal.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN PLA_RENTA FLOAT COMMENT 'Renta a pagar por el empleado.';

ALTER TABLE APL_PLA_PLANILLA MODIFY COLUMN EMP_ID INTEGER COMMENT 'Identificador de empleado.';


CREATE TABLE APL_SAL_SALARIO (
                SAL_ID INT AUTO_INCREMENT NOT NULL,
                SAL_SALARIO DOUBLE  NOT NULL,
                SAL_FECHA_INICIO DATE NOT NULL,
                SAL_FECHA_FIN DATE,
                EMP_ID INT NOT NULL,
                PRIMARY KEY (SAL_ID)
);

ALTER TABLE APL_SAL_SALARIO COMMENT 'Honorarios disponibles para el empleado.';

ALTER TABLE APL_SAL_SALARIO MODIFY COLUMN SAL_ID INTEGER COMMENT 'Identificador de salrio de empleado.';

ALTER TABLE APL_SAL_SALARIO MODIFY COLUMN SAL_SALARIO FLOAT COMMENT 'Salario debengado por el empleado.';

ALTER TABLE APL_SAL_SALARIO MODIFY COLUMN SAL_FECHA_INICIO DATE COMMENT 'Fecha inicio de salario.';

ALTER TABLE APL_SAL_SALARIO MODIFY COLUMN SAL_FECHA_FIN DATE COMMENT 'Fecha fin de salario.';

ALTER TABLE APL_SAL_SALARIO MODIFY COLUMN EMP_ID INTEGER COMMENT 'Identificador de empleado.';


CREATE TABLE APL_TIP_TIPO_USUARIO (
                TIP_ID INT AUTO_INCREMENT NOT NULL,
                TIP_NOMBRE VARCHAR(45) NOT NULL,
                PRIMARY KEY (TIP_ID)
);

ALTER TABLE APL_TIP_TIPO_USUARIO COMMENT 'Tipo de usuario segun nivel de acceso al sistema.';

ALTER TABLE APL_TIP_TIPO_USUARIO MODIFY COLUMN TIP_ID INTEGER COMMENT 'Identificador de tipo usuario.';

ALTER TABLE APL_TIP_TIPO_USUARIO MODIFY COLUMN TIP_NOMBRE VARCHAR(45) COMMENT 'Nombre del tipo de acceso.';


CREATE TABLE APL_USR_USUARIO (
                USR_ID INT AUTO_INCREMENT NOT NULL,
                USR_ACCESO VARCHAR(45) NOT NULL,
                USR_NOMBRE VARCHAR(45) NOT NULL,
                USR_APELLIDO VARCHAR(45) NOT NULL,
                USR_CONTRASENA VARCHAR(35) NOT NULL,
                TIP_ID INT NOT NULL,
                PRIMARY KEY (USR_ID)
);

ALTER TABLE APL_USR_USUARIO COMMENT 'Datos de inicio de sesion del usuario.';

ALTER TABLE APL_USR_USUARIO MODIFY COLUMN USR_ID INTEGER COMMENT 'Identificador de usuario.';

ALTER TABLE APL_USR_USUARIO MODIFY COLUMN USR_ACCESO VARCHAR(45) COMMENT 'Credencial para acceder al sistema.';

ALTER TABLE APL_USR_USUARIO MODIFY COLUMN USR_NOMBRE VARCHAR(45) COMMENT 'Nombre del usuario.';

ALTER TABLE APL_USR_USUARIO MODIFY COLUMN USR_APELLIDO VARCHAR(45) COMMENT 'Apellido del usuario del sistema.';

ALTER TABLE APL_USR_USUARIO MODIFY COLUMN USR_CONTRASENA VARCHAR(35) COMMENT 'Contraseña para acceder al sistema.';

ALTER TABLE APL_USR_USUARIO MODIFY COLUMN TIP_ID INTEGER COMMENT 'Identificador de tipo usuario.';


ALTER TABLE APL_EMP_EMPLEADO ADD CONSTRAINT apl_eci_ecivil_apl_emp_empleado_fk
FOREIGN KEY (ECI_ID)
REFERENCES APL_ECI_ECIVIL (ECI_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_EMP_EMPLEADO ADD CONSTRAINT apl_car_cargo_apl_emp_empleado_fk
FOREIGN KEY (CAR_ID)
REFERENCES APL_CAR_CARGO (CAR_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_EMP_EMPLEADO ADD CONSTRAINT apl_eem_estado_empleado_apl_emp_empleado_fk
FOREIGN KEY (EEM_ID)
REFERENCES APL_EEM_ESTADO_EMPLEADO (EEM_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_EMP_EMPLEADO ADD CONSTRAINT apl_sex_sexo_apl_emp_empleado_fk
FOREIGN KEY (SEX_ID)
REFERENCES APL_SEX_SEXO (SEX_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_DEP_DEPARTAMENTO ADD CONSTRAINT apl_ede_estado_dep_apl_dep_departamento_fk
FOREIGN KEY (EDE_ID)
REFERENCES APL_EDE_ESTADO_DEP (EDE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_EMP_EMPLEADO ADD CONSTRAINT apl_dep_departamento_apl_emp_empleado_fk
FOREIGN KEY (DEP_ID)
REFERENCES APL_DEP_DEPARTAMENTO (DEP_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_SAL_SALARIO ADD CONSTRAINT apl_emp_empleado_apl_sal_salario_fk
FOREIGN KEY (EMP_ID)
REFERENCES APL_EMP_EMPLEADO (EMP_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_PLA_PLANILLA ADD CONSTRAINT apl_emp_empleado_apl_pla_planilla_fk
FOREIGN KEY (EMP_ID)
REFERENCES APL_EMP_EMPLEADO (EMP_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE APL_USR_USUARIO ADD CONSTRAINT apl_tip_tipo_usuario_apl_usr_usuario_fk
FOREIGN KEY (TIP_ID)
REFERENCES APL_TIP_TIPO_USUARIO (TIP_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
